---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Simulation-based sample size calculations for recurrent events with competing deaths

## Download from Github

```{r install}
require(devtools)
devtools::install_github("JulieKFurberg/simpowerrecurrent", force = TRUE)
require(simpowerrecurrent)

# A couple extra packages
require(ggplot2)
require(survival)
require(mets)
```


## Simulation of a single data set


```{r example}
mu0 <- function(time, a){a  * time^2}
S0 <- function(time, b){b * time}


times <- seq(0, 100, by = 25)

cumhaz_mu <- data.frame(time = times,
                        cumhaz = mu0(time = times, a = 0.1))

cumhaz_S <- data.frame(time = times,
                       cumhaz = S0(time = times, b = 0.01))
# Visual
ggplot(aes(x = time, y = cumhaz), data = cumhaz_mu) +
  geom_line() + ggtitle("Mu_0(t) for recurrent events") +
  geom_point()
ggplot(aes(x = time, y = cumhaz), data = cumhaz_S) +
  geom_line() + ggtitle("Lambda_0^D(t) for death") + geom_point()

# Simulating a single data set
sim1 <- simrecurprop(n = 100, 
                     beta = 0,
                     gamma = 0,
                     mu0 = cumhaz_mu,
                     Lam0D = cumhaz_S,
                     crate = 0.01,
                     accrualtime = 0,
                     admincens = 8000)

head(sim1)

# Overview of the data set
with(sim1, table(Z, status))

```


## Esitimation of power for previous example

```{r powerest}
simres1 <- powerest(nsims = 100, n = 100, mu0 = cumhaz_mu, Lam0D = cumhaz_S, alpha = 0.05)

simres1

```



